// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.shri.conference.domain;

import com.shri.conference.domain.SpeakerIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SpeakerIntegrationTest_Roo_Configurable {
    
    declare @type: SpeakerIntegrationTest: @Configurable;
    
}
