// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.shri.conference.domain;

import com.shri.conference.domain.Speaker;
import com.shri.conference.domain.SpeakerDataOnDemand;
import com.shri.conference.domain.Talk;
import com.shri.conference.domain.TalkDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TalkDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TalkDataOnDemand: @Component;
    
    private Random TalkDataOnDemand.rnd = new SecureRandom();
    
    private List<Talk> TalkDataOnDemand.data;
    
    @Autowired
    private SpeakerDataOnDemand TalkDataOnDemand.speakerDataOnDemand;
    
    public Talk TalkDataOnDemand.getNewTransientTalk(int index) {
        Talk obj = new Talk();
        setSpeaker(obj, index);
        return obj;
    }
    
    public void TalkDataOnDemand.setSpeaker(Talk obj, int index) {
        Speaker speaker = speakerDataOnDemand.getRandomSpeaker();
        obj.setSpeaker(speaker);
    }
    
    public Talk TalkDataOnDemand.getSpecificTalk(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Talk obj = data.get(index);
        Long id = obj.getId();
        return Talk.findTalk(id);
    }
    
    public Talk TalkDataOnDemand.getRandomTalk() {
        init();
        Talk obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Talk.findTalk(id);
    }
    
    public boolean TalkDataOnDemand.modifyTalk(Talk obj) {
        return false;
    }
    
    public void TalkDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Talk.findTalkEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Talk' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Talk>();
        for (int i = 0; i < 10; i++) {
            Talk obj = getNewTransientTalk(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
