// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.shri.conference.domain;

import com.shri.conference.domain.TalkIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TalkIntegrationTest_Roo_Configurable {
    
    declare @type: TalkIntegrationTest: @Configurable;
    
}
